name: default

channels:
  - conda-forge

dependencies:
  - python=3.7.7
  - pip=20.2.4
  - ipykernel=5.3.4
  - pip:
    # Linters
    - yapf==0.30.0
    - pylint==2.6.0
    - yamllint==1.23.0
    # AML
    - azureml-core==1.22.0
    - azureml-defaults==1.22.0
    # DS
    - pandas==1.2.3
    - numpy==1.20.1
    - seaborn==0.11.1
    - matplotlib==3.3.3
    - joblib==1.0.1