name: default

channels:
  - conda-forge

dependencies:
  - python=3.7.7
  - pip=20.2.4
  - ipykernel=5.3.4
  - pip:
    - yapf==0.30.0
    - pylint==2.6.0
    - yamllint==1.23.0
    - pandas==1.1.5
    - azureml-core==1.22.0
    - azureml-defaults==1.22.0
    - seaborn==0.11.1
    - matplotlib==3.3.3