name: default

channels:
  - conda-forge

dependencies:
  - python=3.7.7
  - pip=20.2.4
  - ipykernel=5.3.4
  - pip:
    # Linters
    - yapf==0.30.0
    - pylint==2.6.0
    - yamllint==1.23.0
    # AML
    - azureml-core==1.22.0
    - azureml-defaults==1.22.0
    # DS
    - pandas==0.24.2
    - numpy==1.16.2
    - seaborn==0.11.1
    - matplotlib==3.3.3
    - joblib==0.16.0
    - scikit-learn==0.20.3
